#include "global.h"
const UCHAR KeyState[KEYS_NUM] = {
	DIK_W, DIK_A, DIK_S, DIK_D,
	DIK_O,
	DIK_LEFT, DIK_RIGHT, DIK_UP, DIK_DOWN,
	DIK_PGUP, DIK_PGDN,
	DIK_ESCAPE, DIK_SPACE,
	DIK_0, DIK_1, DIK_2, DIK_3, DIK_4, DIK_5, DIK_6, DIK_7, DIK_8, DIK_9,
	DIK_HOME, DIK_END,
	DIK_TAB,
	DIK_F1, DIK_F2, DIK_F3, DIK_F4,
	DIK_LSHIFT
};

UINT G_Flag = 1;